### ISSUE TITLE
Autoinstall script issues

### ISSUE THREAD

**Issue by cksachdev** [theme-next/theme-next.org#53]
Getting following errors, after a fresh auto install.
![image](https://user-images.githubusercontent.com/37770/57329251-0273f200-7131-11e9-8c38-2c9b3e612b63.png)

```
127.0.0.1/:1 Refused to apply style from 'http://127.0.0.1:4000/lib/fancybox/source/jquery.fancybox.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
2(index):1482 GET http://127.0.0.1:4000/lib/fancybox/source/jquery.fancybox.pack.js net::ERR_ABORTED 404 (Not Found)
utils.js?v=7.1.1:38 Uncaught TypeError: $(...).fancybox is not a function
    at Object.wrapImageWithFancyBox (utils.js?v=7.1.1:38)
    at HTMLDocument.<anonymous> (next-boot.js?v=7.1.1:35)
    at j (index.js?v=2.1.3:2)
    at Object.fireWith [as resolveWith] (index.js?v=2.1.3:2)
    at Function.ready (index.js?v=2.1.3:2)
    at HTMLDocument.I (index.js?v=2.1.3:2)
wrapImageWithFancyBox @ utils.js?v=7.1.1:38
(anonymous) @ next-boot.js?v=7.1.1:35
j @ index.js?v=2.1.3:2
fireWith @ index.js?v=2.1.3:2
ready @ index.js?v=2.1.3:2
I @ index.js?v=2.1.3:2
index.js?v=2.1.3:4 
```

**Comment by stevenjoezhang** [comment]
Run `hexo-theme-next-autodeploy.sh`, and `fancybox` will be installed automatically

**Comment by stevenjoezhang** [comment]
Script updated https://github.com/theme-next/theme-next.org/commit/39410dcff4c9f963a9f2d2712b8fdc8bfd217572

**Comment by jiangtj** [comment]
@stevenjoezhang in fact, I prefer site to be a complete project, which can be run after clone, rather than need to execute a shell script to improve. 😂

**Comment by stevenjoezhang** [comment]
The current process is the same as the Hexo website: https://github.com/hexojs/site
and vuejs.org https://github.com/vuejs/vuejs.org/
Maybe we can use a command like `npm start` instead of `sh hexo-theme-next-autoinstall.sh`

See also https://github.com/iissnan/theme-next-docs/

<blockquote><img src="https://avatars0.githubusercontent.com/u/6375567?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/hexojs/site">hexojs/site</a></strong></div><div>The website for Hexo. Contribute to hexojs/site development by creating an account on GitHub.</div></blockquote>
<blockquote><img src="https://avatars1.githubusercontent.com/u/6128107?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/vuejs/vuejs.org">vuejs/vuejs.org</a></strong></div><div>📄 The official documentation site for Vue.js. Contribute to vuejs/vuejs.org development by creating an account on GitHub.</div></blockquote>

**Comment by stevenjoezhang** [comment]
The new process is
```
git clone https://github.com/next-theme/theme-next-docs
cd theme-next-docs
npm install
npx hexo server
```
https://github.com/next-theme/theme-next-docs#getting-started
See also https://github.com/theme-next/theme-next.org/commit/39410dcff4c9f963a9f2d2712b8fdc8bfd217572

<blockquote><img src="https://avatars0.githubusercontent.com/u/63177289?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/next-theme/theme-next-docs">next-theme/theme-next-docs</a></strong></div><div>📖 The documentation for NexT. Contribute to next-theme/theme-next-docs development by creating an account on GitHub.</div></blockquote>
